package Interfaz;

import java.io.*;
import java.sql.*;
import javax.swing.JOptionPane;

public class IBuscar extends javax.swing.JFrame {

    private Connection conector;
    private Statement sentenciador;

    public IBuscar() {
        initComponents();
        conectarDB();
        setLocationRelativeTo(null);
        setTitle("Buscar en el directorio");
        setSize(600, 500);
    }

    private void conectarDB() {
        try {
            conector = DriverManager.getConnection("jdbc:derby://localhost:1527/AgendaDigital", "usuario", "12345");
            sentenciador = conector.createStatement();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR DE CONEXION!\n" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GUItxtbuscar = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();
        GUIbuscaName = new javax.swing.JTextField();
        GUIvolver = new javax.swing.JButton();
        GUIConsultar = new javax.swing.JButton();
        GUIbuscaApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        GUIbuscaApellido2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Digite el primer apellido: ");

        GUIbuscaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIbuscaNameActionPerformed(evt);
            }
        });

        GUIvolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GUIvolver.setText("Volver a Menú");
        GUIvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIvolverActionPerformed(evt);
            }
        });

        GUIConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GUIConsultar.setText("Buscar");
        GUIConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIConsultarActionPerformed(evt);
            }
        });

        GUIbuscaApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIbuscaApellidoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Digite el nombre a consultar: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Digite el segundo apellido:");

        GUIbuscaApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIbuscaApellido2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GUIbuscaName, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(GUIvolver)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GUIConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39)
                                    .addComponent(GUIbuscaApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GUIbuscaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(GUItxtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GUIbuscaName, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GUIbuscaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GUIbuscaApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GUItxtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUIConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GUIvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUIvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIvolverActionPerformed
        volverMenuPrincipal();
    }//GEN-LAST:event_GUIvolverActionPerformed

    private void GUIbuscaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIbuscaNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUIbuscaNameActionPerformed

    private void GUIbuscaApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIbuscaApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUIbuscaApellidoActionPerformed

    private void GUIConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIConsultarActionPerformed
        String nb = GUIbuscaName.getText();
        String ape1 = GUIbuscaApellido.getText();
        String ape2 = GUIbuscaApellido2.getText();
        String msjFinal = "";
        try {
            ResultSet resultado = sentenciador.executeQuery("SELECT * FROM Datosagenda WHERE nombre='"+nb+"' AND primer_apellido='"+ape1+"' AND segundo_apellido='"+ape2+"'");
            while(resultado.next()){
                int cedResultado = resultado.getInt("CEDULA");
                String nbResultado = resultado.getString("NOMBRE");
                String ape1Resultado = resultado.getString("PRIMER_APELLIDO");
                String ape2Resultado = resultado.getString("SEGUNDO_APELLIDO");
                int telResultado = resultado.getInt("TELEFONO");
                String corrResultado = resultado.getString("CORREO_ELECTRÓNICO");// CREO Q AHÍ ESTA EL PROB. CORREO_ELECTRONICO
                msjFinal += "Cedula: " + cedResultado + "\n" + "Nombre: " + nbResultado + "\n" + "Primer Apellido: " + ape1Resultado + "\n" 
                        + "Segundo Apellido: " + ape2Resultado + "\n" + "Telefono: " + telResultado + "\n" + "Correo: " + corrResultado + "\n" 
                        + "--------------------------------------\n";
            }
            GUItxtbuscar.setText(msjFinal);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR DE SELECT!\n" + e);
        }

    }//GEN-LAST:event_GUIConsultarActionPerformed

    private void GUIbuscaApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIbuscaApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUIbuscaApellido2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GUIConsultar;
    private javax.swing.JTextField GUIbuscaApellido;
    private javax.swing.JTextField GUIbuscaApellido2;
    private javax.swing.JTextField GUIbuscaName;
    private java.awt.TextArea GUItxtbuscar;
    private javax.swing.JButton GUIvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void volverMenuPrincipal() {
        IMenu ventana = new IMenu();
        ventana.setVisible(true);
        this.setVisible(false);
    }
}
