/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;

/**
 *
 * @author Veronica
 */
public class IVertodo extends javax.swing.JFrame {

    String nombreArchivo= "Directorio";
    public IVertodo() {
        initComponents();
         setLocationRelativeTo(null);
        setTitle("Ver todo los contactos");
        setSize(600,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GUIvolver1 = new javax.swing.JButton();
        GUItxtVertodo = new java.awt.TextArea();
        GUIVertodo = new javax.swing.JButton();
        GOrdenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        GUIvolver1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GUIvolver1.setText("Volver a Menú");
        GUIvolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIvolver1ActionPerformed(evt);
            }
        });

        GUIVertodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GUIVertodo.setText("Ver todo el directorio");
        GUIVertodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIVertodoActionPerformed(evt);
            }
        });

        GOrdenar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GOrdenar.setText("Ordenar");
        GOrdenar.setEnabled(false);
        GOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(GOrdenar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(GUIVertodo)
                        .addGap(66, 66, 66)
                        .addComponent(GUIvolver1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(GUItxtVertodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(GUItxtVertodo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GUIVertodo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GUIvolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUIvolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIvolver1ActionPerformed
        volverMenuPrincipal();
    }//GEN-LAST:event_GUIvolver1ActionPerformed

    private void GUIVertodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIVertodoActionPerformed
        int elByte; 
      String elmensaje = ""; 
      //String tmp[]=new String[10]
      //Registro r=new Registro();
      
        try {
            InputStream entrada= new FileInputStream(nombreArchivo); 
            try{
               
            while ((elByte= entrada.read())!=-1) {
                /*
                tmp=elByte.split(",");
                
                SE AGREGA al JTABLE DESDE EL TMP
                
                */
                
              elmensaje+=(char)elByte;   
            }
            GUItxtVertodo.setText(elmensaje);
            GUItxtVertodo.setEditable(false);

        } catch (FileNotFoundException e) {
            System.out.println(e);
           }
        }catch (IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_GUIVertodoActionPerformed

    private void GOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOrdenarActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_GOrdenarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GOrdenar;
    private javax.swing.JButton GUIVertodo;
    private java.awt.TextArea GUItxtVertodo;
    private javax.swing.JButton GUIvolver1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
private void volverMenuPrincipal() {
        IMenu ventana = new IMenu();
        ventana.setVisible(true);
        this.setVisible(false);
}}
