/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Veronica
 */
public class IVertodo extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    String ids[] = {"Nombre", "Primer apellido", "Segundo apellido", "Cédula", "Teléfono", "Correo electrónico"};

    String nombreArchivo = "Directorio";

    public IVertodo() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Ver todo los contactos");
        setSize(600, 500);
        tabla1.setModel(modelo);
        modelo.setColumnIdentifiers(ids);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GUIvolver1 = new javax.swing.JButton();
        GUIVertodo = new javax.swing.JButton();
        GOrdenar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        GUIvolver1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GUIvolver1.setText("Volver a Menú");
        GUIvolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIvolver1ActionPerformed(evt);
            }
        });

        GUIVertodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GUIVertodo.setText("Ver todo el directorio");
        GUIVertodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIVertodoActionPerformed(evt);
            }
        });

        GOrdenar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GOrdenar.setText("Ordenar");
        GOrdenar.setEnabled(false);
        GOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOrdenarActionPerformed(evt);
            }
        });

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(GOrdenar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(GUIVertodo)
                        .addGap(66, 66, 66)
                        .addComponent(GUIvolver1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GUIVertodo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GUIvolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUIvolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIvolver1ActionPerformed
        volverMenuPrincipal();
    }//GEN-LAST:event_GUIvolver1ActionPerformed

    private void GUIVertodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIVertodoActionPerformed
        int elByte;
        String elmensaje = "";
        //String tmp[];
        //Registro r=new Registro();
        ArrayList registros=new ArrayList<Registro>();
        try {
            InputStream entrada = new FileInputStream(nombreArchivo);
            try {
                //? 63
                while ((elByte = entrada.read()) != -1) {
                    
                    /*
                     tmp=elByte.split(",");
                
                     SE AGREGA al JTABLE DESDE EL TMP

                    RespuestaEmpleado tmp=new RespuestaEmpleado();
                tmp.setId(respuesta.getId());
                //JOptionPane.showMessageDialog(null, tmp.getId());
                modelo.addRow(new Object[]{String.valueOf(respuesta.getIdEncuesta()), respuesta.getId(), respuesta.getPreg1(), respuesta.getR1(), respuesta.getPreg2(), respuesta.getR2(), respuesta.getPreg3(), respuesta.getR3(), respuesta.getPreg4(), respuesta.getR4(), respuesta.getPreg5(), respuesta.getR5(), respuesta.getPreg6(), respuesta.getR6()});
                 
                    */

                  // String contacto[] = linea.split("%");
                   // JOptionPane.showMessageDialog(null,String.valueOf(elByte));
                    elmensaje += (char) elByte;
                    if(elByte == 63){
                        //JOptionPane.showMessageDialog(null,elByte);
                        String tmp[]=elmensaje.split(",");
                //        JOptionPane.showMessageDialog(null, tmp[0]);
                  //      JOptionPane.showMessageDialog(null, tmp[1]);
                    //    JOptionPane.showMessageDialog(null, tmp[2]);
                        Registro r=new Registro(tmp[0],tmp[1],tmp[2],tmp[3],tmp[4],tmp[5]);
                        registros.add(r);
                        elmensaje="";
                    }
                    
                }
                
                for (int i = 0; i < registros.size(); i++) {
                    Registro r=(Registro)registros.get(i);
                    modelo.addRow(new Object[]{r.getNombre(),r.getApellido1(),r.getApellido2(),r.getCedula(),r.getTelefono(),r.getCorreo()});
                }
                
                
                
               // JOptionPane.showMessageDialog(null,elmensaje);
                //GUItxtVertodo.setText(elmensaje);
                //GUItxtVertodo.setEditable(false);

            } catch (FileNotFoundException e) {
                System.out.println(e);
            }
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_GUIVertodoActionPerformed

    private void GOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOrdenarActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_GOrdenarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GOrdenar;
    private javax.swing.JButton GUIVertodo;
    private javax.swing.JButton GUIvolver1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
private void volverMenuPrincipal() {
        IMenu ventana = new IMenu();
        ventana.setVisible(true);
        this.setVisible(false);
    }

}
